name: markdown_syntax_highlighter
description: syntax highlighter for flutter markdown.
version: 0.0.0
author: Jonathan G.
homepage: https://github.com/gsmlg-dev/syntax_highlighter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9+1
  string_scanner: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

